package dev.lezli.hotrulez.lexer

object FirebaseRulesTokenTypes {
    val KEYWORD = FirebaseRulesTokenType("KEYWORD")
    val CONSTANT = FirebaseRulesTokenType("CONSTANT")
    val OPERATION = FirebaseRulesTokenType("OPERATION")
    val BUILTIN = FirebaseRulesTokenType("BUILTIN")
    val TYPE = FirebaseRulesTokenType("TYPE")
    val FUNCTION_CALL = FirebaseRulesTokenType("FUNCTION_CALL")
    val IDENTIFIER = FirebaseRulesTokenType("IDENTIFIER")
    val STRING = FirebaseRulesTokenType("STRING")
    val NUMBER = FirebaseRulesTokenType("NUMBER")
    val LINE_COMMENT = FirebaseRulesTokenType("LINE_COMMENT")
    val BLOCK_COMMENT = FirebaseRulesTokenType("BLOCK_COMMENT")
    val PATH_SEPARATOR = FirebaseRulesTokenType("PATH_SEPARATOR")
    val L_BRACE = FirebaseRulesTokenType("L_BRACE")
    val R_BRACE = FirebaseRulesTokenType("R_BRACE")
    val L_PAREN = FirebaseRulesTokenType("L_PAREN")
    val R_PAREN = FirebaseRulesTokenType("R_PAREN")
    val L_BRACKET = FirebaseRulesTokenType("L_BRACKET")
    val R_BRACKET = FirebaseRulesTokenType("R_BRACKET")
    val COMMA = FirebaseRulesTokenType("COMMA")
    val DOT = FirebaseRulesTokenType("DOT")
    val COLON = FirebaseRulesTokenType("COLON")
    val SEMICOLON = FirebaseRulesTokenType("SEMICOLON")
    val EQUALS = FirebaseRulesTokenType("EQUALS")
    val STAR_STAR = FirebaseRulesTokenType("STAR_STAR")
    val DOLLAR = FirebaseRulesTokenType("DOLLAR")
    val OPERATOR = FirebaseRulesTokenType("OPERATOR")
}
